package com.mobilabsolutions.payment.sample

import com.mobilabsolutions.payment.sample.payment.PaymentPresenter
import com.mobilabsolutions.payment.sample.registration.RegistrationPresenter


/**
 * Presenter injection is used with dagger as a way of telling dagger that presenters are injectable
 * since the instantiation is done by [DaggerPresenterManager]
 *
 * This class can be easily generated by using annotations and preprocessor
 *
 * @author [Ugljesa Jovanovic](ugi@mobilabsolutions.com)
 */
interface PresenterInjection {

    fun inject(registrationPresenter: RegistrationPresenter)

    fun inject(paymentPresenter: PaymentPresenter)

//    fun inject(loginPresenter: LoginPresenter)
//
//    fun inject(menuPresenter: MenuPresenter)
//
//    fun inject(subMenuPresenter: SubMenuPresenter)
//
//    fun inject(articlePresenter: ArticlePresenter)
//
//    fun inject(userPresenter: LoggedInUserPresenter)
//
//    fun inject(userAccountPresenter: UserAccountPresenter)
//
//    fun inject(paymentMethodPresenter: PaymentMethodPresenter)
}