name: Android CI Github Action Trying

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8

    - uses: vgaidarji/android-github-actions/build@v1.0.0
    - run: ./gradlew assembleDebug
