name: Android CI Github Action Trying

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@master
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8
    - name: Clean Project
      run: ./gradlew clean
      
    - name: Spotless Check
      run: ./gradlew spotlessCheck  
      
    - name: Unit Test
      run: ./gradlew check -x :template-integration:check
