name: Android CI Github Action Trying

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        version: 1.8
    - name: Clean Project
      run: |
       mkdir "$ANDROID_HOME/licenses" || true
       echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
       echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
       ./gradlew clean
      
    - name: Spotless Check
      run: ./gradlew spotlessCheck  
      
    - name: Unit Test
      run: ./gradlew check -x :template-integration:check
